import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyMono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    primaryColor: '#155eef',
    primaryColorHover: '#2970ff',
    primaryColorPressed: '#004eeb',
    primaryColorSuppl: '#155eef',
    infoColor: '#175cd3',
    infoColorHover: '#155eef',
    infoColorPressed: '#004eeb',
    infoColorSuppl: '#175cd3',
    borderColor: '#eaecf0',
    dividerColor: '#eaecf0',
    hoverColor: '#f9fafb',
    tableHeaderColor: '#f9fafb',
    tableColorHover: '#f9fafb',
    textColor1: '#101828',
    textColor2: '#344054',
    textColor3: '#667085',
    placeholderColor: '#98a2b3',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    heightMedium: '40px',
    fontSize: '14px',
    fontSizeMedium: '14px',
    lineHeight: '1.5',
  },
  Button: {
    heightMedium: '40px',
    borderRadiusMedium: '8px',
    fontSizeMedium: '14px',
    textColor: '#344054',
    textColorHover: '#344054',
    textColorPressed: '#344054',
    textColorFocus: '#344054',
    border: '1px solid #d0d5dd',
    borderHover: '1px solid #d0d5dd',
    borderPressed: '1px solid #84adff',
    borderFocus: '1px solid #84adff',
    color: '#ffffff',
    colorHover: '#f9fafb',
    colorPressed: '#f9fafb',
    colorFocus: '#ffffff',
  },
  Card: {
    borderColor: '#eaecf0',
    borderRadius: '8px',
    color: '#ffffff',
    paddingSmall: '8px 24px',
  },
  Drawer: {
    borderRadius: '8px',
    color: '#ffffff',
    textColor: '#344054',
    titleTextColor: '#101828',
    headerBorderBottom: '1px solid #eaecf0',
    bodyPadding: '0',
  },
}
